# https://yarnpkg.com/configuration/yarnrc
# it's enough to have single .yarnrc.yml file - "yarnPath" will be resolved from all the workspaces
enableGlobalCache: false
enableTelemetry: false
nodeLinker: node-modules
pnpEnableEsmLoader: false
yarnPath: .yarn/releases/yarn-4.9.0.cjs
