= JS Monorepo with webpack based application using esbuild based plugins/modules/libraries

.Date: 2025-04-10

When trying to use https://github.com/andytaylor/activemq-artemis-console/tree/hawtio-up[ActiveMQ Artemis Console] as real Hawtio plugin in https://github.com/hawtio/hawtio-next/tree/main/app[Hawtio Application] I found some issue related to how all these bits of code are bundled.

hawtio/hawtio-next repository contains:

* `app` an application built with webpack that uses `@hawtio/react` package. It also uses (to some extent) Webpack Module Federation tooling
* `packages/hawtio` - a package built with tsup (which uses esbuild and rollup) used by the `app`

Artemis Console uses `@hawtio/react`, but doesn't provide own reusable package - it only builds _final_ application using webpack.

The problems started when I extracted library and app code and consumed the library in Hawtio's `app`. I had problems:

* Artemis plugin relied on communication with Jolokia, but it wasn't ready yet (user didn't yet log in into hawtio-connect tab for Artemis broker with Jolokia agent) - rejected promise error
* `ArtemisTable` has React errors (passing object instead of string/function to create component)

I also see a webpack asset/chunk hell created in hawtio - out of 102 files (chunks/assets?) 89 were from Monaco editor.

Can't we have nice "vendored" chunks/bundles/assets?

https://blog.jakoblind.no/code-split-vendors-with-webpack-for-faster-load-speed/

== Another (and different) _blank page_ monorepo with yarn, webpack and tsup

This time before adding yarn I'll start with `.yarnrc.yml`, so when I add yarn, it'll already use `node_modules/` instead of .pnp.cjs`.

To get `packageManager` in `package.json`:
----
$ corepack use yarn
Installing yarn@4.9.0 in the project...

➤ YN0000: · Yarn 4.9.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done in 0s 36ms
----

To get yarn inside the project (so corepack's `yarn` uses our yarn for maximum consistency between devs' envs):
----
$ yarn set version 4.9.0 --yarn-path
➤ YN0000: Downloading https://repo.yarnpkg.com/4.9.0/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-4.9.0.cjs
➤ YN0000: Done in 0s 411ms
----

This added the below like to `.yarnrc.yml`:
----
yarnPath: .yarn/releases/yarn-4.9.0.cjs
----

== Structure

I want to keep:

* `tsup` built libraries/packages under `packages/`
* `webpack` (`rspack`) built applications under `apps/`

All are yarn workspaces.

== React applications

For Nth time - what is the order of turning empty `package.json` into React application that uses Patternfly, webpack, TypeScript (and linter/prettier, jest, ...)?

I started with
----
yarn add -D react react-dom
----

and created empty `src/index.ts`.

Now I think it's already time for a bundler. So adding clean `webpack.config.js` and `yarn add -D webpack webpack-cli`.

[,javascript]
----
export default {
  mode: "development",
  // https://webpack.js.org/configuration/devtool/
  devtool: false,
  entry: {
    "main": "./src/index.ts"
  }
}
----

`index.ts` imports (`import`, not `import()`) `bootstrap.tsx` which does the basic React initialization.

`yarn run webpack` caused:

----
ERROR in ./src/index.ts 1:0-20
Module not found: Error: Can't resolve './bootstrap' in '/data/sources/github.com/grgrzybek/modular-app-showcase/apps/app-simple/src'
----

because it's `import "./bootstrap"` - I always forget what's all about this extensionless importing.

Also IDEA suggests:
----
Try npm i --save-dev @types/react if it exists or add a new declaration (.d.ts) file containing declare module 'react';
----

After adding `@types/react` IDEA shows this:
----
TS1259: Module
"/data/sources/github.com/grgrzybek/modular-app-showcase/node_modules/@types/react/index"
can only be default-imported using the esModuleInterop flag
----

Switching `import React from "react"` to `import * as React from "react"` helped.

But webpack can't build it anyway (it's Typescript after all).

So https://webpack.js.org/guides/typescript/

Actually webpack explains this `import React` vs `import * as React`:

TIP::
To make imports do this by default and keep `import _ from 'lodash';` syntax in TypeScript, set `"allowSyntheticDefaultImports" : true` and `"esModuleInterop" : true` in your `tsconfig.json` file. This is related to TypeScript configuration and mentioned in our guide only for your information.

Webpack recommends `ts-loader` for `.ts` files - highlighting that it's using THE `tsc` from Microsoft, which does full type checking. We'll be using `swc-loader` to make things faster.

----
yarn add -D swc-loader @swc/core
----

Still this extensionless import problem:
----
$ yarn run webpack
asset main.js 1.04 KiB [emitted] (name: main)
runtime modules 274 bytes 1 module
./src/index.ts 22 bytes [built] [code generated]

ERROR in ./src/index.ts 1:0-21
Module not found: Error: Can't resolve './bootstrap' in '/data/sources/github.com/grgrzybek/modular-app-showcase/apps/app-simple/src'
----

`swc-loader` doesn't seem to be using `tsconfig.json`. But it's an issue with webpack configuration fixed with:
----
resolve: {
  extensions: [".ts", ".tsx", ".js", ".jsx"],
},
----

== Webpack code splitting

When there was `index.ts` that imported `bootstrap.tsx` there was just one asset produced - `main.js`.
After switching from `import` to `import()` webpack used https://webpack.js.org/guides/code-splitting/[code splitting].
We can also (I guess) do the same with explicit usage of https://webpack.js.org/plugins/split-chunks-plugin/[SplitChunksPlugin].

SplitChunksPlugin can be used directly in `plugins` configuration array, but also via `optimization.splitChunks`.